---
title: "DogLicensing_clean"
author: "Yakun Wang yw3211"
date: "10/8/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
### load library
library(tidyverse)
library(zipcode)
library(tm)
library(tidytext)
```

```{r}
# Data Processing extract year = 2018
dog2018<-read.csv("NYC_Dog_Licensing_Dataset.csv") %>% filter(Extract.Year==2018)
nyc_neigh_zip <- read.csv('nyc_zipcode.csv')

# Add Age
dog2018$Age<- 2018-dog2018$AnimalBirthMonth

# Add long/lat according to zipcode
dog2018$ZipCode <- as.character(dog2018$ZipCode)
data(zipcode)
dog2018 <- left_join(dog2018, zipcode, by = c("ZipCode"="zip"))

# connect zipcode with neighborhood
neigh_zip <- VCorpus(VectorSource(nyc_neigh_zip$ZIP.Codes))%>%
  tm_map(removePunctuation) %>% 
  tidy() %>%
  select(text, id) %>%
  mutate(id = id) %>%
  unnest_tokens(zipcode, text) %>%
  left_join(., nyc_neigh_zip %>% mutate(id = rownames(nyc_neigh_zip)), by='id' ) %>%
  select(zipcode, Neighborhood)

write.csv(neigh_zip, "nbhd_zip_clean.csv")

# remove dog not in the neighborhood (42)
dog2018 <- dog2018[dog2018$ZipCode %in% neigh_zip$zipcode, ]

# Add neighborhood
dog2018 <- left_join(dog2018, neigh_zip, by = c("ZipCode"="zipcode"))

# Export Data
write.csv(dog2018, "DogLicensing_clean.csv")
```